In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from pathlib import Path

data_raw = Path("../data_raw")
list(data_raw.glob("*.csv"))

[WindowsPath('../data_raw/nasa_exoplanets_raw_2026_07_21.csv.csv')]

In [3]:
csv_file = data_raw / "nasa_exoplanets_raw_2026_07_21.csv.csv"

df = pd.read_csv(csv_file, comment="#")

In [4]:
df.shape

(6324, 127)

In [5]:
df.head()

,loc_rowid,pl_name,hostname,pl_letter,sy_snum,sy_pnum,sy_mnum,cb_flag,discoverymethod,disc_year,...,st_rotperr1,st_rotperr2,st_rotplim,st_radv,st_radverr1,st_radverr2,st_radvlim,sy_dist,sy_disterr1,sy_disterr2
0,1,11 Com b,11 Com,b,2,1,0,0,Radial Velocity,2007,...,NaN,NaN,NaN,43.36898,0.20870,-0.20870,0.0,93.1846,1.9238,-1.9238
1,2,11 UMi b,11 UMi,b,1,1,0,0,Radial Velocity,2009,...,NaN,NaN,NaN,-17.52023,0.15382,-0.15382,0.0,125.3210,1.9765,-1.9765
2,3,14 And b,14 And,b,1,1,0,0,Radial Velocity,2008,...,NaN,NaN,NaN,-59.72633,0.31334,-0.31334,0.0,75.4392,0.7140,-0.7140
3,4,14 Her b,14 Her,b,1,2,0,0,Radial Velocity,2002,...,NaN,NaN,NaN,-13.82260,0.00070,-0.00070,0.0,17.9323,0.0073,-0.0073
4,5,16 Cyg B b,16 Cyg B,b,3,1,0,0,Radial Velocity,1996,...,NaN,NaN,NaN,-28.10000,0.10000,-0.10000,0.0,21.1397,0.0110,-0.0111

In [6]:
df.columns.tolist()

['loc_rowid',
 'pl_name',
 'hostname',
 'pl_letter',
 'sy_snum',
 'sy_pnum',
 'sy_mnum',
 'cb_flag',
 'discoverymethod',
 'disc_year',
 'disc_facility',
 'rv_flag',
 'tran_flag',
 'micro_flag',
 'ima_flag',
 'pl_controv_flag',
 'pl_orbper',
 'pl_orbpererr1',
 'pl_orbpererr2',
 'pl_orbperlim',
 'pl_orbsmax',
 'pl_orbsmaxerr1',
 'pl_orbsmaxerr2',
 'pl_orbsmaxlim',
 'pl_rade',
 'pl_radeerr1',
 'pl_radeerr2',
 'pl_radelim',
 'pl_radj',
 'pl_radjerr1',
 'pl_radjerr2',
 'pl_radjlim',
 'pl_bmasse',
 'pl_bmasseerr1',
 'pl_bmasseerr2',
 'pl_bmasselim',
 'pl_bmassj',
 'pl_bmassjerr1',
 'pl_bmassjerr2',
 'pl_bmassjlim',
 'pl_bmassprov',
 'pl_dens',
 'pl_denserr1',
 'pl_denserr2',
 'pl_denslim',
 'pl_orbeccen',
 'pl_orbeccenerr1',
 'pl_orbeccenerr2',
 'pl_orbeccenlim',
 'pl_insol',
 'pl_insolerr1',
 'pl_insolerr2',
 'pl_insollim',
 'pl_eqt',
 'pl_eqterr1',
 'pl_eqterr2',
 'pl_eqtlim',
 'pl_orbincl',
 'pl_orbinclerr1',
 'pl_orbinclerr2',
 'pl_orbincllim',
 'ttv_flag',
 'pl_trandep',
 'pl_trandeperr1',
 'pl_trandeperr2',
 'pl_trandeplim',
 'pl_ratdor',
 'pl_ratdorerr1',
 'pl_ratdorerr2',
 'pl_ratdorlim',
 'pl_ratror',
 'pl_ratrorerr1',
 'pl_ratrorerr2',
 'pl_ratrorlim',
 'pl_rvamp',
 'pl_rvamperr1',
 'pl_rvamperr2',
 'pl_rvamplim',
 'st_spectype',
 'st_teff',
 'st_tefferr1',
 'st_tefferr2',
 'st_tefflim',
 'st_rad',
 'st_raderr1',
 'st_raderr2',
 'st_radlim',
 'st_mass',
 'st_masserr1',
 'st_masserr2',
 'st_masslim',
 'st_met',
 'st_meterr1',
 'st_meterr2',
 'st_metlim',
 'st_metratio',
 'st_lum',
 'st_lumerr1',
 'st_lumerr2',
 'st_lumlim',
 'st_logg',
 'st_loggerr1',
 'st_loggerr2',
 'st_logglim',
 'st_age',
 'st_ageerr1',
 'st_ageerr2',
 'st_agelim',
 'st_dens',
 'st_denserr1',
 'st_denserr2',
 'st_denslim',
 'st_vsin',
 'st_vsinerr1',
 'st_vsinerr2',
 'st_vsinlim',
 'st_rotp',
 'st_rotperr1',
 'st_rotperr2',
 'st_rotplim',
 'st_radv',
 'st_radverr1',
 'st_radverr2',
 'st_radvlim',
 'sy_dist',
 'sy_disterr1',
 'sy_disterr2']

In [7]:
cols_trabajo = [
    #Organización de las variables relevantes a partir de las clasificaciones propuestas en el catálogo original
    # Identification
    "pl_name", "hostname", "pl_letter",
    
    # System
    "sy_snum", "sy_pnum", "sy_mnum", "cb_flag",
    
    # Discovery
    "discoverymethod", "disc_year", "disc_facility",
    "rv_flag", "tran_flag", "micro_flag", "ima_flag", "ttv_flag",
    "pl_controv_flag",
    
    # Orbital Parameters
    "pl_orbper", "pl_orbsmax", "pl_orbeccen",
    
    # Planetary parameters
    "pl_rade", "pl_bmasse", "pl_bmassprov", "pl_dens",
    "pl_insol", "pl_eqt",
    
    # Stellar parametres
    "st_spectype", "st_teff", "st_rad", "st_mass", "st_met",
    "st_metratio", "st_lum", "st_logg", "st_age",
    
    # Distance
    "sy_dist"
]

df_work = df[cols_trabajo].copy()
df_work.shape

(6324, 35)

In [8]:
#Recolección de información sobre las variables faltantes 
missing = pd.DataFrame({
    "variable": df_work.columns,
    "datos_disponibles": df_work.notna().sum().values,
    "datos_faltantes": df_work.isna().sum().values,
    "porcentaje_faltante": (df_work.isna().mean().values * 100).round(3)
})

missing.sort_values("porcentaje_faltante", ascending=False)

           variable  datos_disponibles  datos_faltantes  porcentaje_faltante
25      st_spectype               2344             3980               62.935
33           st_age               4889             1435               22.691
18      pl_orbeccen               5273             1051               16.619
30      st_metratio               5667              657               10.389
29           st_met               5684              640               10.120
23         pl_insol               5743              581                9.187
24           pl_eqt               5799              525                8.302
17       pl_orbsmax               5898              426                6.736
16        pl_orbper               5981              343                5.424
32          st_logg               5999              325                5.139
27           st_rad               6003              321                5.076
31           st_lum               6009              315                4.981
26          st_teff               6027              297                4.696
22          pl_dens               6183              141                2.230
19          pl_rade               6274               50                0.791
20        pl_bmasse               6293               31                0.490
34          sy_dist               6297               27                0.427
28          st_mass               6315                9                0.142
1          hostname               6324                0                0.000
15  pl_controv_flag               6324                0                0.000
2         pl_letter               6324                0                0.000
3           sy_snum               6324                0                0.000
4           sy_pnum               6324                0                0.000
5           sy_mnum               6324                0                0.000
6           cb_flag               6324                0                0.000
7   discoverymethod               6324                0                0.000
8         disc_year               6324                0                0.000
9     disc_facility               6324                0                0.000
10          rv_flag               6324                0                0.000
11        tran_flag               6324                0                0.000
12       micro_flag               6324                0                0.000
21     pl_bmassprov               6324                0                0.000
13         ima_flag               6324                0                0.000
14         ttv_flag               6324                0                0.000
0           pl_name               6324                0                0.000

In [9]:
output_path = "../data_processed/01_variables_seleccionadas.csv"
df_work.to_csv(output_path, index=False)

In [10]:
print("Número de planetas:", len(df_work))
print("Número de estrellas anfitrionas:", df_work["hostname"].nunique())
print("Métodos de descubrimiento:", df_work["discoverymethod"].nunique())

Número de planetas: 6324
Número de estrellas anfitrionas: 4738
Métodos de descubrimiento: 11

In [11]:
missing_path = "../tables/tabla_valores_faltantes.csv"
missing.sort_values("porcentaje_faltante", ascending=False).to_csv(missing_path, index=False)

missing_path

'../tables/tabla_valores_faltantes.csv'

In [12]:
muestras = {
    "muestra_total": len(df_work),
    "sin_controversiales": len(df_work[df_work["pl_controv_flag"] == 0]),
    "con_radio": df_work["pl_rade"].notna().sum(),
    "con_masa": df_work["pl_bmasse"].notna().sum(),
    "con_densidad_reportada": df_work["pl_dens"].notna().sum(),
    "con_radio_y_masa": df_work[["pl_rade", "pl_bmasse"]].dropna().shape[0],
    "con_metalicidad": df_work["st_met"].notna().sum(),
    "con_masa_estelar": df_work["st_mass"].notna().sum(),
    "con_temperatura_estelar": df_work["st_teff"].notna().sum(),
    "con_radio_masa_metalicidad": df_work[["pl_rade", "pl_bmasse", "st_met"]].dropna().shape[0],
}

tabla_muestras = pd.DataFrame(
    muestras.items(),
    columns=["submuestra", "numero_de_planetas"]
)

tabla_muestras

                   submuestra  numero_de_planetas
0               muestra_total                6324
1         sin_controversiales                6267
2                   con_radio                6274
3                    con_masa                6293
4      con_densidad_reportada                6183
5            con_radio_y_masa                6250
6             con_metalicidad                5684
7            con_masa_estelar                6315
8     con_temperatura_estelar                6027
9  con_radio_masa_metalicidad                5615

In [13]:
df_clean = df_work[df_work["pl_controv_flag"] == 0].copy()

df_clean.to_csv("../data_processed/02_catalogo_limpio_base.csv", index=False)

df_clean.shape

(6267, 35)

In [14]:
tabla_muestras.to_csv("../tables/tabla_submuestras.csv", index=False)

In [16]:
## Revisión de duplicados y consistencia de los datos a utilizar 
print("Filas duplicadas completas:", df_work.duplicated().sum())
print("Planetas duplicados por nombre:", df_work["pl_name"].duplicated().sum())
print("Nombres únicos de planetas:", df_work["pl_name"].nunique())
print("Filas totales:", len(df_work))

Filas duplicadas completas: 0
Planetas duplicados por nombre: 0
Nombres únicos de planetas: 6324
Filas totales: 6324

In [17]:
checks_fisicos = {
    "radio_planetario_menor_o_igual_cero": (df_work["pl_rade"] <= 0).sum(),
    "masa_planetaria_menor_o_igual_cero": (df_work["pl_bmasse"] <= 0).sum(),
    "densidad_menor_o_igual_cero": (df_work["pl_dens"] <= 0).sum(),
    "periodo_orbital_menor_o_igual_cero": (df_work["pl_orbper"] <= 0).sum(),
    "semieje_mayor_menor_o_igual_cero": (df_work["pl_orbsmax"] <= 0).sum(),
    "temperatura_estelar_menor_o_igual_cero": (df_work["st_teff"] <= 0).sum(),
    "masa_estelar_menor_o_igual_cero": (df_work["st_mass"] <= 0).sum(),
    "radio_estelar_menor_o_igual_cero": (df_work["st_rad"] <= 0).sum(),
    "distancia_menor_o_igual_cero": (df_work["sy_dist"] <= 0).sum(),
}

tabla_checks_fisicos = pd.DataFrame(
    checks_fisicos.items(),
    columns=["revision", "numero_de_casos"]
)

tabla_checks_fisicos

                                 revision  numero_de_casos
0     radio_planetario_menor_o_igual_cero                0
1      masa_planetaria_menor_o_igual_cero                0
2             densidad_menor_o_igual_cero                0
3      periodo_orbital_menor_o_igual_cero                0
4        semieje_mayor_menor_o_igual_cero                0
5  temperatura_estelar_menor_o_igual_cero                0
6         masa_estelar_menor_o_igual_cero                0
7        radio_estelar_menor_o_igual_cero                0
8            distancia_menor_o_igual_cero                0

In [18]:
print("Resumen Notebook 01")
print("-------------------")
print("Catálogo original:", df.shape)
print("Catálogo con variables seleccionadas:", df_work.shape)
print("Catálogo limpio sin controversiales:", df_clean.shape)
print("Filas duplicadas completas:", df_work.duplicated().sum())
print("Planetas duplicados por nombre:", df_work["pl_name"].duplicated().sum())
print("Valores físicos imposibles encontrados:", tabla_checks_fisicos["numero_de_casos"].sum())

Resumen Notebook 01
-------------------
Catálogo original: (6324, 127)
Catálogo con variables seleccionadas: (6324, 35)
Catálogo limpio sin controversiales: (6267, 35)
Filas duplicadas completas: 0
Planetas duplicados por nombre: 0
Valores físicos imposibles encontrados: 0

In [22]:
# Revisión de tipos de datos en variables seleccionadas

tipos_variables = pd.DataFrame({
    "variable": df_work.columns,
    "tipo": df_work.dtypes.astype(str).values
})

tipos_variables

           variable     tipo
0           pl_name   object
1          hostname   object
2         pl_letter   object
3           sy_snum    int64
4           sy_pnum    int64
5           sy_mnum    int64
6           cb_flag    int64
7   discoverymethod   object
8         disc_year    int64
9     disc_facility   object
10          rv_flag    int64
11        tran_flag    int64
12       micro_flag    int64
13         ima_flag    int64
14         ttv_flag    int64
15  pl_controv_flag    int64
16        pl_orbper  float64
17       pl_orbsmax  float64
18      pl_orbeccen  float64
19          pl_rade  float64
20        pl_bmasse  float64
21     pl_bmassprov   object
22          pl_dens  float64
23         pl_insol  float64
24           pl_eqt  float64
25      st_spectype   object
26          st_teff  float64
27           st_rad  float64
28          st_mass  float64
29           st_met  float64
30      st_metratio   object
31           st_lum  float64
32          st_logg  float64
33           st_age  float64
34          sy_dist  float64

In [23]:
tipos_variables.to_csv("../tables/tabla_tipos_variables.csv", index=False)

In [26]:
unidades = {
    "pl_orbper": "días",
    "pl_orbsmax": "au",
    "pl_orbeccen": "adimensional",
    "pl_rade": "radios terrestres",
    "pl_bmasse": "masas terrestres",
    "pl_dens": "g/cm^3",
    "pl_insol": "flujo terrestre",
    "pl_eqt": "K",
    "st_teff": "K",
    "st_rad": "radios solares",
    "st_mass": "masas solares",
    "st_met": "dex",
    "st_lum": "log10(luminosidad solar)",
    "st_logg": "log10(cm/s^2)",
    "st_age": "Gyr",
    "sy_dist": "pc"
}

tabla_unidades = pd.DataFrame(
    unidades.items(),
    columns=["variable", "unidad"]
)

tabla_unidades

tabla_unidades.to_csv("../tables/tabla_unidades_variables.csv", index=False)

## Pipeline reproducible de limpieza inicial
df_raw      = catálogo original completo
df_work     = catálogo con variables seleccionadas
df_clean    = catálogo limpio sin planetas controversiales
df_derived  = catálogo con variables derivadas, como densidad calculada

### Criterios de inclusión y exclusión

Criterios de inclusión:
- Planetas presentes en la tabla `Planetary Systems Composite Parameters`.
- Planetas con nombre identificable (`pl_name`).
- Sistemas con estrella anfitriona identificable (`hostname`).
- Variables seleccionadas relevantes para el análisis poblacional.

Criterios de exclusión:
- Planetas marcados como controversiales (`pl_controv_flag = 1`).
- Filas duplicadas completas, si existieran.
- Registros con valores físicamente imposibles en variables principales, si existieran.

In [27]:
def limpiar_catalogo_exoplanetas(ruta_raw):
    """
    Carga el catálogo original del NASA Exoplanet Archive,
    selecciona variables relevantes, revisa consistencia básica
    y excluye planetas controversiales.

    Parámetros
    ----------
    ruta_raw : str o Path
        Ruta al archivo CSV original.

    Retorna
    -------
    df_raw : DataFrame
        Catálogo original completo.
    df_work : DataFrame
        Catálogo con variables seleccionadas.
    df_clean : DataFrame
        Catálogo limpio base sin planetas controversiales.
    tabla_missing : DataFrame
        Tabla de valores faltantes por variable.
    tabla_muestras : DataFrame
        Tabla de tamaños de submuestras.
    tabla_checks_fisicos : DataFrame
        Tabla de revisiones físicas básicas.
    """

    # 1. Cargar catálogo original
    df_raw = pd.read_csv(ruta_raw, comment="#")

    # 2. Variables seleccionadas
    cols_trabajo = [
        # Identificación
        "pl_name", "hostname", "pl_letter",

        # Sistema
        "sy_snum", "sy_pnum", "sy_mnum", "cb_flag",

        # Descubrimiento
        "discoverymethod", "disc_year", "disc_facility",
        "rv_flag", "tran_flag", "micro_flag", "ima_flag", "ttv_flag",
        "pl_controv_flag",

        # Parámetros orbitales
        "pl_orbper", "pl_orbsmax", "pl_orbeccen",

        # Parámetros planetarios
        "pl_rade", "pl_bmasse", "pl_bmassprov", "pl_dens",
        "pl_insol", "pl_eqt",

        # Parámetros estelares
        "st_spectype", "st_teff", "st_rad", "st_mass", "st_met",
        "st_metratio", "st_lum", "st_logg", "st_age",

        # Distancia
        "sy_dist"
    ]

    df_work = df_raw[cols_trabajo].copy()

    # 3. Tabla de valores faltantes
    tabla_missing = pd.DataFrame({
        "variable": df_work.columns,
        "datos_disponibles": df_work.notna().sum().values,
        "datos_faltantes": df_work.isna().sum().values,
        "porcentaje_faltante": (df_work.isna().mean().values * 100).round(3)
    }).sort_values("porcentaje_faltante", ascending=False)

    # 4. Tabla de submuestras
    muestras = {
        "muestra_total": len(df_work),
        "sin_controversiales": len(df_work[df_work["pl_controv_flag"] == 0]),
        "con_radio": df_work["pl_rade"].notna().sum(),
        "con_masa": df_work["pl_bmasse"].notna().sum(),
        "con_densidad_reportada": df_work["pl_dens"].notna().sum(),
        "con_radio_y_masa": df_work[["pl_rade", "pl_bmasse"]].dropna().shape[0],
        "con_metalicidad": df_work["st_met"].notna().sum(),
        "con_masa_estelar": df_work["st_mass"].notna().sum(),
        "con_temperatura_estelar": df_work["st_teff"].notna().sum(),
        "con_radio_masa_metalicidad": df_work[["pl_rade", "pl_bmasse", "st_met"]].dropna().shape[0],
    }

    tabla_muestras = pd.DataFrame(
        muestras.items(),
        columns=["submuestra", "numero_de_planetas"]
    )

    # 5. Revisión de valores físicos imposibles
    checks_fisicos = {
        "radio_planetario_menor_o_igual_cero": (df_work["pl_rade"] <= 0).sum(),
        "masa_planetaria_menor_o_igual_cero": (df_work["pl_bmasse"] <= 0).sum(),
        "densidad_menor_o_igual_cero": (df_work["pl_dens"] <= 0).sum(),
        "periodo_orbital_menor_o_igual_cero": (df_work["pl_orbper"] <= 0).sum(),
        "semieje_mayor_menor_o_igual_cero": (df_work["pl_orbsmax"] <= 0).sum(),
        "temperatura_estelar_menor_o_igual_cero": (df_work["st_teff"] <= 0).sum(),
        "masa_estelar_menor_o_igual_cero": (df_work["st_mass"] <= 0).sum(),
        "radio_estelar_menor_o_igual_cero": (df_work["st_rad"] <= 0).sum(),
        "distancia_menor_o_igual_cero": (df_work["sy_dist"] <= 0).sum(),
    }

    tabla_checks_fisicos = pd.DataFrame(
        checks_fisicos.items(),
        columns=["revision", "numero_de_casos"]
    )

    # 6. Revisión de duplicados
    if df_work.duplicated().sum() > 0:
        df_work = df_work.drop_duplicates().copy()

    # 7. Excluir planetas controversiales
    df_clean = df_work[df_work["pl_controv_flag"] == 0].copy()

    return df_raw, df_work, df_clean, tabla_missing, tabla_muestras, tabla_checks_fisicos

In [32]:
ruta_raw = Path("../data_raw/nasa_exoplanets_raw_2026_07_21.csv")

df_raw_test, df_work_test, df_clean_test, missing_test, muestras_test, checks_test = limpiar_catalogo_exoplanetas(ruta_raw)

In [33]:
print("Catálogo raw:", df_raw_test.shape)
print("Catálogo variables seleccionadas:", df_work_test.shape)
print("Catálogo limpio base:", df_clean_test.shape)

print("\nDuplicados completos:", df_work_test.duplicated().sum())
print("Planetas duplicados por nombre:", df_work_test["pl_name"].duplicated().sum())
print("Valores físicos imposibles:", checks_test["numero_de_casos"].sum())

Catálogo raw: (6324, 127)
Catálogo variables seleccionadas: (6324, 35)
Catálogo limpio base: (6267, 35)

Duplicados completos: 0
Planetas duplicados por nombre: 0
Valores físicos imposibles: 0

In [34]:
df_work_test.to_csv("../data_processed/01_variables_seleccionadas.csv", index=False)
df_clean_test.to_csv("../data_processed/02_catalogo_limpio_base.csv", index=False)

missing_test.to_csv("../tables/tabla_valores_faltantes.csv", index=False)
muestras_test.to_csv("../tables/tabla_submuestras.csv", index=False)
checks_test.to_csv("../tables/tabla_revision_valores_fisicos.csv", index=False)